---
- hosts: node1, node2
  vars:
    max_requests: 200
  remote_user: ansible
  tasks:
  - name: inclure variables OS
    include_vars: {{ item }}
    with_first_found:
      - "{{ ansible_facts.os_family }}.yml"
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
    become: yes
    become_method: sudo
  - name: copy success index
    copy:
      src: /tmp/ansible/index.html
      dest: "{{ docroot }}/index.html"
      owner: {{ apache_user }}
      group: {{ apache_group }}
    become: yes
    notify:
    - restart apache
  - name: write the apache config file
    template:
      src: /tmp/ansible/{{ apache_conf }}.j2
      dest: /{{ apache_conf_path }}/{{ apache_conf }}
    become: yes
    become_method: sudo
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: {{ apache_service }}
      state: started
    become: yes
    become_method: sudo
  handlers:
    - name: restart apache
      service:
        name: {{ apache_service }}
        state: restarted
      become: yes
      become_method: sudo

